### ISSUE TITLE
Repository 이름 변경

### ISSUE THREAD

**Issue by Yoonkyoungme** [TastyJapan/tasty-japan-web#1]
**Describe the bug**
해당 Repository에 react project를 생성하려고 하는데, Repository 이름 때문에 생성 오류가 발생한다.
오류는 다음과 같다.

Cannot create a project named "TastyJapan-Web" because of npm naming restrictions:
name can no longer contain capital letters
Please choose a different project name.

**To Reproduce**
Repository 이름을 tasty-japan-web으로 변경한다.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Chocochip101** [comment]
tasty-japan-web으로 수정했습니다.
